### ISSUE TITLE
Depuis que j'ai acheté je n'arrive pas à utiliser mon bitcoin

### ISSUE THREAD

**Issue by Knk11** [0xPolygon/staking-contracts#18]
Depuis que j'ai acheté je n'arrive pas à utiliser mon bitcoin 

_Originally posted by @Koita95200 in https://github.com/Blockchair/Blockchair.Support/issues/806#issuecomment-1079758668_

**Comment by Aleksao998** [comment]
Translate to this question is
`Since I bought I can't use my bitcoin`
Closing this issue as it is not relevant
