### ISSUE TITLE
@AhmedIbrahim336 do you still want to be listed, I can fix this PR, but it might show the tvl as 0

### ISSUE THREAD

**Issue by Knk11** [0xPolygon/staking-contracts#22]
@AhmedIbrahim336 do you still want to be listed, I can fix this PR, but it might show the tvl as 0

_Originally posted by @g1nt0ki in https://github.com/DefiLlama/DefiLlama-Adapters/pull/2801#issuecomment-1148818035_

**Comment by Aleksao998** [comment]
closing, spam

**Comment by AhmedIbrahim336** [comment]
@Aleksao998 Sorry it is not spam I just was not available lately. If we can reopen the PR I will fix it!
