### ISSUE TITLE
polygon staking contract address

### ISSUE THREAD

**Issue by roccomuso** [0xPolygon/staking-contracts#6]
Is it right to assume that this `0x5e3ef299fddf15eaa0432e6e66473ace8c13d908` is the STAKING_CONTRACT_ADDRESS for Polygon on ethereum mainnet?

**Comment by zivkovicmilos** [comment]
Hey @roccomuso,

We've updated the docs to include information on PoS:
https://sdk-docs.polygon.technology/docs/consensus/pos-concepts

We're also in the process of providing PoS officially through the Polygon SDK:
https://github.com/0xPolygon/polygon-sdk/pull/219
